alpha main menu
Suchpuns/machiavellian-pursuits pull request #12
Opened 2024-01-13 07:29 UTC by echochase

** CHANGES - PLEASE REVIEW SINCE ITS MY FIRST TIME N I DONT CODE TOO WELL **

- added resources (button, mainmenu background)
- added menubutton
- added style files

anyway not much but still i dont wanna pollute w bad code

2024-01-13 07:42 UTC, Suchpuns requested changes

2024-01-13 07:42 UTC, Suchpuns commented on client/src/App.css
> -#root {
Feel free to just delete this instead of commenting it out

2024-01-13 07:42 UTC, Suchpuns commented on client/src/App.tsx
> -import { useState } from 'react'
You don't want this in App.tsx
make a Menu.tsx and put your code there.
then put Menu.tsx inside App.tsx to test it out.

2024-01-13 07:42 UTC, Suchpuns commented on client/src/App.tsx
> -import { useState } from 'react'
main reason is cuz we are gonna have other routes 
say /game or /room
So App.tsx is gonna need to have the components for each of those routes.
if that didn't make much sense lemme know and I can show you.

2024-01-13 07:42 UTC, Suchpuns commented on client/src/App.tsx
> -import { useState } from 'react'
MainMenu.tsx*

2024-01-13 08:21 UTC, Suchpuns commented on client/src/Styles/MainMenu.css
> +    width: 100vw;
add
background-position: center;

to actually center the background

2024-01-13 08:21 UTC, Suchpuns commented on client/src/Resources/Other/MainMenu.png
logo is not centred

2024-01-13 08:21 UTC, Suchpuns commented on client/src/Resources/Other/MainMenu.png
also increase the width, its not long enough for my laptop screen 💀

2024-01-13 08:24 UTC, echochase commented on client/src/Resources/Other/MainMenu.png
yepyep leaving this till after we decide on logo

2024-01-15 13:02 UTC, Suchpuns approved these changes
LGTM

2024-01-15 13:02 UTC, merged